"use client";

import { useState } from "react";
import {
  Activity,
  AlertCircle,
  FileSearch,
  Sparkles,
  Zap,
} from "lucide-react";
import { AnalysisResults } from "@/components/analysis-results";
import { IntegrationPanel } from "@/components/integration-panel";
import { LoadingSpinner } from "@/components/loading-spinner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { SAMPLE_INCIDENT } from "@/lib/sample-incident";
import type { AnalyzeResponse, GrafanaConfig, JiraConfig } from "@/lib/types";
import {
  DEFAULT_GRAFANA_CONFIG,
  DEFAULT_JIRA_CONFIG,
} from "@/lib/types";

function OutputPanel({
  loading,
  result,
  compact = false,
}: {
  loading: boolean;
  result: AnalyzeResponse | null;
  compact?: boolean;
}) {
  return (
    <Card
      className={`border-border/50 bg-card/40 backdrop-blur-sm ${compact ? "sticky top-8" : ""}`}
    >
      <CardHeader>
        <CardTitle className="text-lg">Analysis Output</CardTitle>
        <CardDescription>
          Structured post-incident report generated by AI
        </CardDescription>
      </CardHeader>
      <CardContent>
        {loading && <LoadingSpinner />}
        {!loading && !result && (
          <div className="text-muted-foreground flex flex-col items-center justify-center gap-3 py-16 text-center">
            <div className="rounded-full bg-muted/50 p-4">
              <Sparkles className="text-muted-foreground/60 size-8" />
            </div>
            <p className="text-sm">
              Submit incident data to generate your report
            </p>
          </div>
        )}
        {!loading && result && (
          <div className={compact ? "max-h-[70vh] overflow-y-auto pr-1" : ""}>
            <AnalysisResults result={result} compact={compact} />
          </div>
        )}
      </CardContent>
    </Card>
  );
}

export function IncidentInvestigator() {
  const [incidentText, setIncidentText] = useState("");
  const [jira, setJira] = useState<JiraConfig>(DEFAULT_JIRA_CONFIG);
  const [grafana, setGrafana] = useState<GrafanaConfig>(DEFAULT_GRAFANA_CONFIG);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AnalyzeResponse | null>(null);

  const loadSample = () => {
    setIncidentText(SAMPLE_INCIDENT);
    setError(null);
    setResult(null);
    setGrafana((prev) => ({
      ...prev,
      incidentStart: "2026-05-14T08:07",
      incidentEnd: "2026-05-14T08:59",
      serviceName: "payment-api",
    }));
    setJira((prev) => ({
      ...prev,
      issueKey: "INC-2026-0514",
      channelName: "#inc-0514-payments",
    }));
  };

  const analyze = async () => {
    if (!incidentText.trim() && !jira.enabled && !grafana.enabled) {
      setError("Provide incident logs or enable at least one integration.");
      return;
    }

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          incidentText,
          jira: jira.enabled ? jira : undefined,
          grafana: grafana.enabled ? grafana : undefined,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error ?? "Analysis failed.");
      }

      setResult(data as AnalyzeResponse);
    } catch (err) {
      setError(err instanceof Error ? err.message : "An unexpected error occurred.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mx-auto max-w-7xl space-y-8 px-4 py-8 sm:px-6 lg:px-8">
      <header className="space-y-4">
        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="outline" className="border-primary/30 text-primary">
            <Activity className="size-3" />
            SRE Platform
          </Badge>
          <Badge variant="secondary">AI-Powered</Badge>
        </div>
        <div className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Incident Investigator
          </h1>
          <p className="text-muted-foreground max-w-2xl text-base leading-relaxed">
            Transform raw incident logs, war-room transcripts, and observability
            data into structured post-incident reports with executive summaries,
            root cause analysis, and prevention recommendations.
          </p>
        </div>
      </header>

      <div className="grid gap-6 xl:grid-cols-5">
        <div className="space-y-4 xl:col-span-3">
          <Card className="border-border/50 bg-card/40 backdrop-blur-sm">
            <CardHeader>
              <div className="flex items-start justify-between gap-4">
                <div>
                  <CardTitle className="flex items-center gap-2 text-lg">
                    <FileSearch className="text-primary size-5" />
                    Incident Input
                  </CardTitle>
                  <CardDescription>
                    Paste logs, alerts, war-room transcripts, or runbook notes
                  </CardDescription>
                </div>
                <Button variant="outline" size="sm" onClick={loadSample}>
                  <Zap className="size-3.5" />
                  Load example
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <Textarea
                placeholder="Paste incident logs, PagerDuty alerts, Slack war-room transcripts, Grafana snapshots…"
                value={incidentText}
                onChange={(e) => setIncidentText(e.target.value)}
                className="min-h-[320px] resize-y font-mono text-xs leading-relaxed sm:min-h-[400px] sm:text-sm"
              />

              <IntegrationPanel
                jira={jira}
                grafana={grafana}
                onJiraChange={setJira}
                onGrafanaChange={setGrafana}
              />

              {error && (
                <div className="flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2.5 text-sm text-destructive">
                  <AlertCircle className="mt-0.5 size-4 shrink-0" />
                  <span>{error}</span>
                </div>
              )}

              <Button
                size="lg"
                className="w-full sm:w-auto"
                onClick={analyze}
                disabled={loading}
              >
                {loading ? (
                  <>
                    <Sparkles className="size-4 animate-pulse" />
                    Processing…
                  </>
                ) : (
                  <>
                    <Sparkles className="size-4" />
                    Analyze Incident
                  </>
                )}
              </Button>
            </CardContent>
          </Card>
        </div>

        <div className="hidden xl:col-span-2 xl:block">
          <OutputPanel loading={loading} result={result} compact />
        </div>
      </div>

      <div className="xl:hidden">
        {(loading || result) && (
          <OutputPanel loading={loading} result={result} />
        )}
      </div>
    </div>
  );
}
